### ISSUE TITLE
Documentation for using purescript-rxjs 

### ISSUE THREAD

**Issue by LukaJCB** [jasonzoladz/purescript-rxjs#1]
I'd love to see how I could integrate this project into mine :) 
Not exactly sure how to do that right now, so any kind of documentation would be nice

**Comment by jasonzoladz** [comment]
I haven't added integration documentation because I want to add tests before releasing to bower and pursuit.  However, the easiest way is to just add this
 ```javascript
 "dependencies": {
   // Other dependencies here,
    "purescript-rxjs": "git://github.com/jasonzoladz/purescript-rxjs.git"
  }
```
in your bower dependencies.  Then `bower install`.  

I'll add this to the README now.

**Comment by LukaJCB** [comment]
Hey, any update on when you'll publish the docs? I'd like to publish a library based on purescript-rxjs, and it'd be great, if there were docs for it on pursuit :)

**Comment by LukaJCB** [comment]
I was thinking we could add the marble diagrams present in the implementations of the other Rx flavours. If you like I could even start publishing them.

**Comment by jasonzoladz** [comment]
Re: publishing to pursuit...  I think we should add tests for the `*Subjects` and integrate `AjaxObservable` first.

Re: marble diagrams..  I think we should just point users to the official diagrams via a link.

**Comment by LukaJCB** [comment]
Hmm okay, maybe you're right about publishing to pursuit. But maybe publish a version to Bower?

**Comment by LukaJCB** [comment]
Also I disagree about the marble diagrams. They might not be seen as all that useful right now, but once `psc-ide` implements inline documentation, I think it'd be an absolute killer feature :)

**Comment by jasonzoladz** [comment]
Release is up.  Feel free to add the marble diagrams if you'd like.  (My thinking is that, since this lib is just a wrapper, the source of truth should be the reactivex.io repo.  However, I don't feel strongly about it.)
