### ISSUE TITLE
Alt instance should behave the same as Semigroup instance

### ISSUE THREAD

**Issue by LukaJCB** [jasonzoladz/purescript-rxjs#12]
Right now we have `concat` for semigroup and `merge` for `Alt`. I think we should make it consistent across type classes. My vote goes for `merge` as `concat` is rarely used if ever.

**Comment by jasonzoladz** [comment]
Agree.

**Comment by jasonzoladz** [comment]
Though we should document `concat` with a **`Note:...`** as it's behavior will be surprising to some users.

**Comment by LukaJCB** [comment]
What kind of Note would you like to see?

**Comment by jasonzoladz** [comment]
The instances are now consistent.  Thanks, Luka!
