### ISSUE TITLE
Add ObservableT Monad transformer

### ISSUE THREAD

**Issue by LukaJCB** [jasonzoladz/purescript-rxjs#15]
I've noticed that usually when we have observables they're often effectful. FromEvent or create are effectful and really most are, especially when dealing with Ajax or the Dom. 

I think a Monad transformer would go a long way to ease those pains and reduce boilerplate.

**Comment by jasonzoladz** [comment]
Sorry for the delay in responding.

I think it's a good idea.  We ought have something like `ObservableT`.  Question:  Should we, first, create an `ObservableLike` typeclass?  (I'm reluctant to have `BehaviorSubjectT`, et al.)

I generally have mixed feelings about increasing cognitive load via richer types (as I'd like to see Haskell/PureScript have wider adoption).  But I suppose the reality is that anyone using Haskell/PureScript in production must embrace them.  (And, heck, it's lighter than the cognitive load of, say, the nonsense that is iOS `UIKit`.)

**Comment by LukaJCB** [comment]
Any feedback on this @jasonzoladz? I could also just publish another library with the transformer.

**Comment by jasonzoladz** [comment]
I'm fine with adding a separate module for `ObservableT`.  Send a PR if you'd like to have it added.  (Note:  Once it's added, I'll do a new release for 0.11.*.)

I'm not sure it saves boilerplate, however...  `runObservableT`, `liftEff`, `liftAff`, etc.

**Comment by LukaJCB** [comment]
So I've started implementing most of the Observable functions on `ObservableT`. One problem I'm facing (or one annoyance), is that now we have 5 different of every single operator in scope when we depend on `purescript-rxjs`. This is especially annoying, when you type something like `merge` and the psc-ide gives you 5 different suggestions for `merge`, `mergeAll` and `mergeMap`. Maybe we should give Subjects their own package? Or maybe we should `ObservableT` its own package, I'm not sure yet.

**Comment by jasonzoladz** [comment]
I wish Scala was a better language, but you really can't beat the granularity of its import scoping.

I think we should just live with qualified imports here, since I think it's better than separating things into other packages.  PureScript ecosystem suffers too much of this already.  See: http://taylor.fausak.me/2016/02/28/neon-an-alternative-purescript-prelude/

**Comment by LukaJCB** [comment]
Yeah I agree it's a problem. But I also want a good experience for using these libraries, so I'm thinking of maybe publishing a package that is ObservableT only for a framework (OutWatch) so you don't get all the extra imports you don't want or need.

**Comment by jasonzoladz** [comment]
Sounds good.  Thanks again for all of your contributions (and blogposts)!
