### ISSUE TITLE
Allow a Subject to subscribe to an Observable

### ISSUE THREAD

**Issue by LukaJCB** [jasonzoladz/purescript-rxjs#2]
Right now when I call 

`subscribe subject observable`

I get the following error:

> Could not match type 
>   `Record`
> with type
>    `BehaviorSubject`
> while trying to match type 

    { next :: forall e. a -> Eff e Unit
    , error :: forall e. Error -> Eff e Unit
    , completed :: forall e. Unit -> Eff e Unit
    }
>  with `BehaviorSubject a`

**Comment by jasonzoladz** [comment]
Sure.  Obviously, however, the functions will be `subscribe<SubjectType>To` as we can't overload.

**Comment by LukaJCB** [comment]
Yeah true, although, maybe `subscriber` should be a typeclass?

**Comment by LukaJCB** [comment]
Came up with this on the fly:

    class Subscriber s where
      next      :: forall a e. a -> Eff e Unit
      error     :: forall e. Error -> Eff e Unit
      completed :: forall e. Unit -> Eff e Unit

If I get the project set up correcly I could probably send a PR, if you're open to that :)

**Comment by jasonzoladz** [comment]
Let me think about it.  I like to avoid adding new typeclasses until its really awkward without it.

**Comment by jasonzoladz** [comment]
For now, I've added `subscribeObservableTo` to each of the `*Subject` modules until we have a better idea on how to put together the appropriate type class(es).

Feel free to put together a PR if you think it makes sense.
