### ISSUE TITLE
how to subscribe?

### ISSUE THREAD

**Issue by piton182** [jasonzoladz/purescript-rxjs#20]
I can't fix types when I subscribe like [here](https://github.com/piton182/purescript-observable-simple).

How can one subscribe with **_subscribe_**, not **_subscribeNext_**?

**Comment by jasonzoladz** [comment]
Sorry for the delayed reply; I was on vacation.

You could fix types by explicitly annotating your `Subscriber`.  The generic type is:

```purescript
type Subscriber a
   =  { next      :: forall e. a -> Eff e Unit
      , error     :: forall e. Error -> Eff e Unit
      , completed :: forall e. Unit -> Eff e Unit
      }
```
But you could do:

```purescript
intSubscriber :: Subscriber Int
intSubscriber = . . .
```

`subscribeNext` is used only when you want to subscribe an effectful computation to an existing stream.  The FFI looks is this:

```javascript
exports.subscribeNext = function (eff){
  return function(obs){
    return function(){
      obs.subscribe(
       function(val){return eff(val)();}
          );
      };
   };
 }
```
