### ISSUE TITLE
Quickcheck required?

### ISSUE THREAD

**Issue by justinwoo** [jasonzoladz/purescript-rxjs#21]
Looks like it's required here: https://github.com/jasonzoladz/purescript-rxjs/blob/a0ebb531278fc23508c9beaf98df5a3ec24d24a4/src/RxJS/Observable.purs#L111

But if this is needed in tests, maybe a newtype instance would remove the need for it. Otherwise it seems like I can't build this package without this installed.

**Comment by jasonzoladz** [comment]
Hi Justin,

Sorry for the delayed reply.  I've been traveling for work and won't have time to solve this until I return.  I'll get in touch shortly after 10/6.

--Jason

**Comment by jasonzoladz** [comment]
Fixed.  e324572f3cf204d3d6f420e3cfb251c033cd39b9
