### ISSUE TITLE
startWith doesn't work correctly

### ISSUE THREAD

**Issue by LukaJCB** [jasonzoladz/purescript-rxjs#3]
Currently `startWith` requires an `Array`. My thoughts here were, that every item of the Array would be prepended to the Observable, however what actually happens is that just the Array get prepended. This of course completely breaks the type safety and will throw errors at runtime.

I see two solutions right now, either change the type signature to:

    foreign import startWith :: forall a. a -> Observable a -> Observable a

or change the underlying JS code to actually parse the array and prepend all the items individually.

We could of course have both as well, with something like `startWith` and `startWithAll`or `startWithMany`.

I've fixed this in my own version, and will gladly send a PR if you decide to go down of these paths. :)

**Comment by jasonzoladz** [comment]
Good catch.

 A PR is definitely welcome.  

(Aside: I wish that we had the ...spread operator here as it would be more performant.)  I think we should have a `startWithOne`  and a `startWithMany`, making sure to note in the documentation that `startWithMany` is a very expensive operation for long arrays (as it'll reverse the input array and then invoke `startWith` n-times).

**Comment by jasonzoladz** [comment]
Fixed by #4
