### ISSUE TITLE
'TypeError: obs.subscribe is not a function' when calling `empty`

### ISSUE THREAD

**Issue by LukaJCB** [jasonzoladz/purescript-rxjs#7]
full stack trace:

TypeError: obs.subscribe is not a function
    at /Users/luka/proj/purescript-rxjs/output/RxJS.Observable/foreign.js:38:11
    at __do (/Users/luka/proj/purescript-rxjs/output/Test.Main/index.js:33:57)
    at /Users/luka/proj/purescript-rxjs/output/Control.Monad.Aff/foreign.js:269:16
    at /Users/luka/proj/purescript-rxjs/output/Test.Unit/foreign.js:23:7
    at /Users/luka/proj/purescript-rxjs/output/Control.Monad.Aff/foreign.js:214:12
    at /Users/luka/proj/purescript-rxjs/output/Control.Monad.Aff/foreign.js:176:17
    at /Users/luka/proj/purescript-rxjs/output/Control.Monad.Aff/foreign.js:182:25
    at /Users/luka/proj/purescript-rxjs/output/Control.Monad.Aff/foreign.js:275:5
    at /Users/luka/proj/purescript-rxjs/output/Control.Monad.Aff/foreign.js:176:17
    at /Users/luka/proj/purescript-rxjs/output/Control.Monad.Aff/foreign.js:176:17

**Comment by jasonzoladz** [comment]
Fixed by #10
