### ISSUE TITLE
'TypeError: obs.subscribe is not a function' when calling `never`

### ISSUE THREAD

**Issue by LukaJCB** [jasonzoladz/purescript-rxjs#8]
Full stack trace:

TypeError: obs.subscribe is not a function
    at /Users/luka/proj/purescript-rxjs/output/RxJS.Observable/foreign.js:38:11
    at __do (/Users/luka/proj/purescript-rxjs/output/Test.Main/index.js:33:57)
    at /Users/luka/proj/purescript-rxjs/output/Control.Monad.Aff/foreign.js:269:16
    at /Users/luka/proj/purescript-rxjs/output/Test.Unit/foreign.js:23:7
    at /Users/luka/proj/purescript-rxjs/output/Control.Monad.Aff/foreign.js:214:12
    at /Users/luka/proj/purescript-rxjs/output/Control.Monad.Aff/foreign.js:176:17
    at /Users/luka/proj/purescript-rxjs/output/Control.Monad.Aff/foreign.js:182:25
    at /Users/luka/proj/purescript-rxjs/output/Control.Monad.Aff/foreign.js:275:5
    at /Users/luka/proj/purescript-rxjs/output/Control.Monad.Aff/foreign.js:176:17
    at /Users/luka/proj/purescript-rxjs/output/Control.Monad.Aff/foreign.js:176:17

**Comment by LukaJCB** [comment]
I'm guessing both this and #7  is because the foreign function is never called, so just the function handle is returned (should be fixed by simply adding a `()` at the end.)

**Comment by jasonzoladz** [comment]
@LukaJCB 

Thanks so much for raising these.

Issues like these are the reason that I haven't yet put together a release.  I need to write tests.  (A startup that I'm working on will use this wrapper in production, so a release is forthcoming, but it's not a major priority over the next few weeks.)

I'm happy to take pull requests on any of these issues.  Otherwise, I'll start picking a few off this weekend.

**Comment by LukaJCB** [comment]
I just added a PR, that fixes the issues I found today and also added a full test suite and some more documentation (been working in my own branch on this for some time now :) and I still see more work to come from me) I'd love to see a release + maybe a travis build soon! (I can help there as well, if you'd like)

**Comment by jasonzoladz** [comment]
Fixed by #10
